# Generated by Django 2.1.2 on 2018-12-10 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('brands', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('categories_fr', models.TextField(null=True)),
                ('image_url', models.TextField(max_length=255, null=True)),
                ('nutrition_grade_fr', models.CharField(max_length=1, null=True)),
                ('countries_fr', models.CharField(max_length=255, null=True)),
                ('fat_100g', models.FloatField(null=True)),
                ('saturated_fat_100g', models.FloatField(null=True)),
                ('sugars_100g', models.FloatField(null=True)),
                ('salt_100g', models.FloatField(null=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('substitute', models.ManyToManyField(related_name='_food_substitute_+', to='foods.Food')),
            ],
        ),
    ]
