# Generated by Django 2.1.2 on 2018-10-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='my_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Foods'),
        ),
    ]
