# Generated by Django 2.1.2 on 2018-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20181101_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='substitute',
        ),
        migrations.AddField(
            model_name='foods',
            name='substitute',
            field=models.ManyToManyField(blank=True, null=True, related_name='_foods_substitute_+', to='foods.Foods'),
        ),
    ]
