# Generated by Django 2.1.2 on 2018-10-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20181023_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='score',
        ),
        migrations.AddField(
            model_name='foods',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='nutrition_grades',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.Foods'),
        ),
    ]
