# Generated by Django 2.1.2 on 2018-11-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20181108_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='substitute',
        ),
        migrations.AddField(
            model_name='foods',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.Foods'),
        ),
    ]
