# Generated by Django 2.1.2 on 2018-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20181108_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='brands',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
