# Generated by Django 2.1.2 on 2018-11-29 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0005_auto_20181109_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='nutrition_grades',
        ),
        migrations.AddField(
            model_name='foods',
            name='nutrition_grade_fr',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='foods',
            name='author',
        ),
        migrations.AddField(
            model_name='foods',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foods',
            name='brands',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.Foods'),
        ),
    ]
