# Generated by Django 2.1.2 on 2018-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20181129_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
