# Generated by Django 2.1.2 on 2018-11-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_foods_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
