# Generated by Django 2.1.2 on 2018-11-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20181130_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
