# Generated by Django 2.1.2 on 2018-11-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20181130_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
