# Generated by Django 2.1.2 on 2018-11-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20181130_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='categories_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='categories_tag',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
