# Generated by Django 2.1.2 on 2018-11-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_auto_20181130_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
