# Generated by Django 2.1.2 on 2018-11-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_auto_20181130_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='categories_tags',
        ),
    ]
