# Generated by Django 2.1.2 on 2018-11-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_auto_20181130_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='countires_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
