# Generated by Django 2.1.2 on 2018-11-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_foods_countires_fr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='countires_fr',
            new_name='countries_fr',
        ),
    ]
