# Generated by Django 2.1.2 on 2018-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_auto_20181130_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
