# Generated by Django 2.1.2 on 2018-12-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_auto_20181130_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['nutrition_grade_fr']},
        ),
    ]
