# Generated by Django 2.1.2 on 2018-12-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_auto_20181201_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['pk']},
        ),
    ]
