# Generated by Django 2.1.2 on 2018-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0020_auto_20181203_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='substitute',
        ),
        migrations.AddField(
            model_name='foods',
            name='substitute',
            field=models.ManyToManyField(related_name='_foods_substitute_+', to='foods.Foods'),
        ),
    ]
