# Generated by Django 2.1.2 on 2018-12-05 10:20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0021_auto_20181203_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('brands', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('categories_fr', models.TextField(null=True)),
                ('image_url', models.TextField(max_length=255, null=True)),
                ('nutrition_grade_fr', models.CharField(max_length=1, null=True)),
                ('countries_fr', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('substitute', models.ManyToManyField(related_name='_food_substitute_+', to='foods.Food')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='foods',
            name='author',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='substitute',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
