# Generated by Django 2.1.2 on 2018-12-05 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0022_auto_20181205_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='countries_fr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
    ]
