# Generated by Django 2.1.2 on 2018-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0024_auto_20181205_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('brands', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('categories_fr', models.TextField(null=True)),
                ('image_url', models.TextField(max_length=255, null=True)),
                ('nutrition_grade_fr', models.CharField(max_length=1, null=True)),
                ('countries_fr', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
