# Generated by Django 2.1.2 on 2018-12-05 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0025_staging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='created_at',
            new_name='created_datetime',
        ),
        migrations.AddField(
            model_name='food',
            name='last_modified_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
