# Generated by Django 2.1.2 on 2018-12-05 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0026_auto_20181205_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_datetime',
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='staging',
            name='last_modified_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='last_modified_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
