# Generated by Django 2.1.2 on 2018-12-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0031_auto_20181205_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staging',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='last_modified_datetime',
        ),
    ]
