# Generated by Django 2.1.2 on 2018-12-06 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0032_auto_20181205_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
