# Generated by Django 2.1.2 on 2018-12-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0034_remove_food_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
