# Generated by Django 2.1.2 on 2018-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0035_auto_20181208_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fat_100g',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='salt_100g',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat_100g',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sugars_100g',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
