# Generated by Django 2.1.2 on 2018-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0036_auto_20181210_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugars_100g',
            field=models.FloatField(null=True),
        ),
    ]
